### ISSUE TITLE
A memo about `default` param of `<cms:gpc>` tag

### ISSUE THREAD

**Issue by trendoman** [GroveOS/GroveOS#1]
https://github.com/GroveOS/GroveOS/blob/7cd04a8205d48a532825c3656f6feb67325b0a2d/grove.sh#L28-L31

Not an issue per se, just a memo. Above block may be written simpler with **default** parameter of `<cms:gpc>`:

```xml
<cms:capture into='request.grove_key'>
    <cms:gpc 'grove_key' method='post' default="<cms:gpc 'grove_key' method='get' />" />
</cms:capture>
```

**However** it does not make sense anyway to provide the **method** parameter e.g. following will work too (keeping the original logic):

```xml
<cms:capture into='request.grove_key' trim='1'>
    <cms:gpc 'grove_key'  />
</cms:capture>
```

(edit: added a **trim** param. it's a native param for `<cms:capture>` and makes capturing values easier.

Why? 

1. PHP reads variables (and replaces ther values) in the default order GET > POST (see https://www.php.net/manual/en/ini.core.php#ini.request_order), so that means that POST has more importance over GET.
2. CouchCMS's tag `<cms:gpc>` will read `$_REQUEST` superglobal array in case **method** is not specified. And that superglobal will be filled according to the point (1).

In practice this means the variable ***request.grove_key*** will be filled from POST by default and if posted value is not present, then from GET.

Congratulations on the commit. It's nice to see the GroveOS growing.

P.S. Email!!!

**Comment by matthewlarkin** [comment]
Beautiful, Anton; I appreciate the tip regarding PHP filling value with GET then POST. Thank you as always sir!
